platform :ios, '8.0'  
target 'GCDProject' do  
pod 'AFNetworking', '~> 3.0'
pod 'Reveal-iOS-SDK', :configurations => ['Debug']
pod 'SDWebImage'
pod 'Masonry'
pod 'MJRefresh'
pod 'JSONModel'
pod 'Ono'
pod 'DTCoreText'
pod 'FMDB'
pod 'ReactiveCocoa', '=2.3'
pod 'FDFullscreenPopGesture'
end
